from __future__ import annotations

from datetime import datetime
from typing import Any

from pydantic import BaseModel, Field


class PredictionRequest(BaseModel):
    """Feature values required by the trained models."""

    return_1: float = Field(
        ...,
        description="Percentage return of the current candle.",
        examples=[0.0012],
    )
    ma_gap: float = Field(
        ...,
        description="Gap between the current price and moving average.",
        examples=[-0.0021],
    )
    volatility_10: float = Field(
        ...,
        ge=0,
        description="Rolling 10-candle return volatility.",
        examples=[0.0045],
    )
    candle_body_ratio: float = Field(
        ...,
        ge=0,
        description="Candle body size relative to candle range.",
        examples=[0.62],
    )
    rsi_14: float = Field(
        ...,
        ge=0,
        le=100,
        description="Fourteen-period Relative Strength Index.",
        examples=[54.3],
    )


class ModelMetrics(BaseModel):
    """Historical evaluation metrics for one model."""

    accuracy: float
    balanced_accuracy: float
    precision: float
    recall: float
    f1: float
    roc_auc: float


class IndividualModelPrediction(BaseModel):
    """Prediction generated by one trained model."""

    model_name: str
    predicted_class: int
    direction: str
    probability_up: float
    probability_down: float
    confidence: float
    threshold: float
    historical_metrics: ModelMetrics | None = None


class EnsemblePrediction(BaseModel):
    """Majority-vote result from all loaded models."""

    method: str
    predicted_class: int
    direction: str
    up_votes: int
    down_votes: int


class RecommendedModel(BaseModel):
    """Model selected using the configured evaluation metric."""

    name: str
    selection_metric: str
    score: float


class PredictionResponse(BaseModel):
    """Predictions from all models and the ensemble decision."""

    predictions: list[IndividualModelPrediction]
    ensemble: EnsemblePrediction
    recommended_model: RecommendedModel


class HealthResponse(BaseModel):
    """Application health response."""

    status: str
    model_loaded: bool
    loaded_model_count: int
    timestamp: datetime


class ModelDetails(BaseModel):
    """Information about one loaded model artifact."""

    name: str
    artifact_path: str
    loaded: bool
    metrics: ModelMetrics | None = None


class ModelInfoResponse(BaseModel):
    """Information about all currently loaded models."""

    loaded_model_count: int
    feature_columns: list[str]
    models: list[ModelDetails]
    recommended_model: RecommendedModel | None = None


class LatestPredictionMetadata(BaseModel):
    """Metadata describing the latest market observation."""

    ticker: str = Field(examples=["GC=F"])
    market_timestamp: str
    generated_at: str


class LatestPredictionResponse(BaseModel):
    """Response returned by the latest prediction endpoint."""

    metadata: LatestPredictionMetadata
    features: dict[str, float]
    predictions: dict[str, Any]